export const countryListConstants = {
  IND: "India",
  PAK: "Pakistan",
  AUS: "Australia",
  BER: "Bermuda",
  BNG: "Bangladesh",
  CAN: "Canada",
  ENG: "England",
  IRE: "Ireland",
  NZ: "New Zealand",
  RSA: "South Aftrica",
  WI: "West Indies",
  ZIM: "Zimbabwe",
  INDIA: "IND",
  PAKISTAN: "PAK",
  AUSTRALIA: "AUS",
  BERMUDA: "BER",
  CANADA: "CAN",
  ENGLAND: "ENG",
  IRELAND: "IRE",
  NEWZEALAND: "NZ",
  SOUTHAFRICA: "RSA",
  WESTINDIES: "WI",
  ZIMBABWE: "ZIM",
};
